### ISSUE TITLE
I'm strugging setting up the config file

### ISSUE THREAD

**Issue by rexy666** [pdemarco925/homebridge-doorsensor#3]
Could it be possible to get a complete config file for reference? I'm confused on where exactly the lines should be added at, and I'm getting erros all the time.

**Comment by rexy666** [comment]
A good night sleep can do wonders sometimes. I guess it was easier when one is not sleep deprived. 

```
{
	"bridge":
	{
		"name": "Homebridge",
		...
		...
		...
	},

	"platforms":
	[
		{
			"platform": "ZWayServer",
			...
			...
			...
		}
	],

	"accessories":
	[
		{
			"accessory": "DoorSensor",
			...
			...
			...
		}
	]
}
```

**Comment by pdemarco925** [comment]
Always. :)
